version: '3.1'
services:
  bot: 
    build: .
    # environment:
    #   PORT: 8092
    # ports:
    #   - "5000:8092"

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: senhaloca123
    ports:
      - "5432:5432"
